import AppKit
import Darwin
import Foundation

public struct PasteboardSourceApplication {
    let bundleIdentifier: String?
    let localizedName: String?

    public init(bundleIdentifier: String?, localizedName: String?) {
        self.bundleIdentifier = bundleIdentifier
        self.localizedName = localizedName
    }

    init(_ runningApplication: NSRunningApplication?) {
        self.bundleIdentifier = runningApplication?.bundleIdentifier
        self.localizedName = runningApplication?.localizedName
    }
}

enum PrivacyFilter {
    private static let privateMarkerTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    private static let privateTypeFragments: [String] = [
        "1password",
        "onepassword",
        "agilebits",
        "concealed",
        "transient"
    ]

    private static let onePasswordSourceFragments: [String] = [
        "1password",
        "onepassword",
        "agilebits"
    ]

    private static let browserSourceFragments: [String] = [
        "com.google.chrome",
        "google chrome",
        "com.apple.safari",
        "safari",
        "org.mozilla.firefox",
        "firefox",
        "com.microsoft.edgemac",
        "microsoft edge",
        "com.brave.browser",
        "brave browser",
        "company.thebrowser.browser",
        "arc",
        "org.chromium.chromium",
        "chromium",
        "com.vivaldi.vivaldi",
        "vivaldi"
    ]

    static func shouldSkip(items: [NSPasteboardItem], sourceApplication: PasteboardSourceApplication?) -> Bool {
        if containsPrivateMarker(items: items) {
            return true
        }
        if isOnePasswordSource(sourceApplication) {
            return true
        }
        if isBrowserSource(sourceApplication),
           let plainText = PasteboardPlainTextExtractor.plainText(from: items),
           isLikelyBrowserCredential(plainText) {
            return true
        }
        return false
    }

    static func containsPrivateMarker(items: [NSPasteboardItem]) -> Bool {
        var containsAutoGeneratedMarker = false
        for item in items {
            for type in item.types where isPrivateMarkerType(type.rawValue) {
                if type.rawValue == "org.nspasteboard.AutoGeneratedType" {
                    containsAutoGeneratedMarker = true
                } else {
                    return true
                }
            }
        }
        return containsAutoGeneratedMarker && !isSpreadsheetCellCopy(items)
    }

    static func isMarkerType(_ typeIdentifier: String) -> Bool {
        isPrivateMarkerType(typeIdentifier)
    }

    private static func isPrivateMarkerType(_ typeIdentifier: String) -> Bool {
        if privateMarkerTypes.contains(typeIdentifier) {
            return true
        }
        let normalized = typeIdentifier.lowercased()
        return privateTypeFragments.contains { normalized.contains($0) }
    }

    private static func isSpreadsheetCellCopy(_ items: [NSPasteboardItem]) -> Bool {
        guard PasteboardPlainTextExtractor.plainText(from: items) != nil else {
            return false
        }

        return items.contains { item in
            if item.types.contains(where: { type in
                let normalized = type.rawValue.lowercased()
                return normalized.contains("google")
                    && (normalized.contains("grid") || normalized.contains("spreadsheet"))
            }) {
                return true
            }

            for type in item.types where type.rawValue.lowercased().contains("html") {
                let html = item.string(forType: type)
                    ?? item.data(forType: type).flatMap { String(data: $0, encoding: .utf8) }
                if html?.range(of: "<table", options: .caseInsensitive) != nil {
                    return true
                }
            }
            return false
        }
    }

    private static func isOnePasswordSource(_ app: PasteboardSourceApplication?) -> Bool {
        guard let app else {
            return false
        }
        let bundleID = app.bundleIdentifier?.lowercased() ?? ""
        let name = app.localizedName?.lowercased() ?? ""
        return onePasswordSourceFragments.contains { fragment in
            bundleID.contains(fragment) || name.contains(fragment)
        }
    }

    private static func isBrowserSource(_ app: PasteboardSourceApplication?) -> Bool {
        guard let app else {
            return false
        }
        let identity = "\(app.bundleIdentifier ?? "") \(app.localizedName ?? "")".lowercased()
        return browserSourceFragments.contains { identity.contains($0) }
    }

    private static func isLikelyBrowserCredential(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.count >= 8, trimmed.count <= 256 else {
            return false
        }
        guard !trimmed.contains(where: \.isNewline) else {
            return false
        }
        guard UUID(uuidString: trimmed) == nil else {
            return false
        }
        guard !isURL(trimmed), !isEmailAddress(trimmed), !isHexColor(trimmed) else {
            return false
        }

        if isLikelyMemorablePassword(trimmed) {
            return true
        }
        if trimmed.contains(where: \.isWhitespace) {
            return false
        }

        let categories = characterCategoryCount(trimmed)
        let hasSymbol = trimmed.contains { !$0.isLetter && !$0.isNumber }
        if trimmed.count >= 8,
           categories >= 3,
           hasSymbol,
           shannonEntropy(trimmed) >= 2.6 {
            return true
        }
        if trimmed.count >= 12,
           categories >= 3,
           shannonEntropy(trimmed) >= 3.2 {
            return true
        }
        if trimmed.count >= 16,
           categories >= 2,
           shannonEntropy(trimmed) >= 3.6 {
            return true
        }
        return false
    }

    private static func isURL(_ text: String) -> Bool {
        guard let url = URL(string: text), let scheme = url.scheme else {
            return false
        }
        return ["http", "https", "file"].contains(scheme.lowercased())
    }

    private static func isEmailAddress(_ text: String) -> Bool {
        let parts = text.split(separator: "@")
        guard parts.count == 2 else {
            return false
        }
        return parts[0].isEmpty == false && parts[1].contains(".")
    }

    private static func isHexColor(_ text: String) -> Bool {
        let trimmed = text.hasPrefix("#") ? String(text.dropFirst()) : text
        guard [3, 4, 6, 8].contains(trimmed.count) else {
            return false
        }
        return trimmed.allSatisfy(\.isHexDigit)
    }

    private static func isLikelyMemorablePassword(_ text: String) -> Bool {
        guard text.contains("-") || text.contains("_") || text.contains(".") else {
            return false
        }
        let parts = text.split { character in
            character == "-" || character == "_" || character == "."
        }
        guard (3...8).contains(parts.count) else {
            return false
        }
        return parts.allSatisfy { part in
            (3...20).contains(part.count) && part.allSatisfy { $0.isLetter || $0.isNumber }
        }
    }

    private static func characterCategoryCount(_ text: String) -> Int {
        var categories = Set<String>()
        for character in text {
            if character.isLowercase {
                categories.insert("lower")
            } else if character.isUppercase {
                categories.insert("upper")
            } else if character.isNumber {
                categories.insert("number")
            } else if !character.isWhitespace {
                categories.insert("symbol")
            }
        }
        return categories.count
    }

    private static func shannonEntropy(_ text: String) -> Double {
        guard !text.isEmpty else {
            return 0
        }
        var counts: [Character: Int] = [:]
        for character in text {
            counts[character, default: 0] += 1
        }
        let length = Double(text.count)
        return counts.values.reduce(0) { result, count in
            let probability = Double(count) / length
            return result - probability * log2(probability)
        }
    }
}
