import AppKit
import Foundation

public struct PasteboardSourceApplication {
    let bundleIdentifier: String?
    let localizedName: String?

    public init(bundleIdentifier: String?, localizedName: String?) {
        self.bundleIdentifier = bundleIdentifier
        self.localizedName = localizedName
    }

    init(_ runningApplication: NSRunningApplication?) {
        self.bundleIdentifier = runningApplication?.bundleIdentifier
        self.localizedName = runningApplication?.localizedName
    }
}

enum PrivacyFilter {
    static let markerTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    private static let privateTypeFragments: [String] = [
        "1password",
        "onepassword",
        "agilebits",
        "concealed",
        "transient",
        "autogenerated",
        "password",
        "secret"
    ]

    private static let passwordBundleFragments: [String] = [
        "1password",
        "agilebits",
        "bitwarden",
        "lastpass",
        "dashlane",
        "keepass",
        "keeper",
        "nordpass",
        "enpass",
        "roboform"
    ]

    private static let browserBundleFragments: [String] = [
        "com.google.chrome",
        "com.brave.browser",
        "company.thebrowser.browser",
        "com.microsoft.edgemac",
        "org.mozilla.firefox",
        "com.apple.safari",
        "com.operasoftware.opera",
        "com.vivaldi.vivaldi"
    ]

    private static let browserNameFragments: [String] = [
        "chrome",
        "brave",
        "arc",
        "edge",
        "firefox",
        "safari",
        "opera",
        "vivaldi"
    ]

    static func shouldSkip(items: [NSPasteboardItem], sourceApplication: PasteboardSourceApplication?) -> Bool {
        if containsPrivateMarker(items: items) {
            return true
        }
        if isLikelyPasswordManager(sourceApplication) {
            return true
        }
        return isLikelyBrowserExtensionSecret(items: items, sourceApplication: sourceApplication)
    }

    static func containsPrivateMarker(items: [NSPasteboardItem]) -> Bool {
        items.contains { item in
            item.types.contains { type in
                isMarkerType(type.rawValue)
            }
        }
    }

    static func isMarkerType(_ typeIdentifier: String) -> Bool {
        if markerTypes.contains(typeIdentifier) {
            return true
        }
        let normalized = typeIdentifier.lowercased()
        return privateTypeFragments.contains { normalized.contains($0) }
    }

    private static func isLikelyPasswordManager(_ app: PasteboardSourceApplication?) -> Bool {
        guard let app else {
            return false
        }
        let bundleID = app.bundleIdentifier?.lowercased() ?? ""
        let name = app.localizedName?.lowercased() ?? ""
        return passwordBundleFragments.contains { fragment in
            bundleID.contains(fragment) || name.contains(fragment)
        }
    }

    private static func isLikelyBrowser(_ app: PasteboardSourceApplication?) -> Bool {
        guard let app else {
            return false
        }
        let bundleID = app.bundleIdentifier?.lowercased() ?? ""
        let name = app.localizedName?.lowercased() ?? ""
        return browserBundleFragments.contains { bundleID.contains($0) }
            || browserNameFragments.contains { name.contains($0) }
    }

    private static func isLikelyBrowserExtensionSecret(
        items: [NSPasteboardItem],
        sourceApplication: PasteboardSourceApplication?
    ) -> Bool {
        guard isLikelyBrowser(sourceApplication) else {
            return false
        }

        let texts = plainTextValues(from: items)
        guard !texts.isEmpty else {
            return false
        }
        return texts.contains(where: isLikelySecretText)
    }

    private static func plainTextValues(from items: [NSPasteboardItem]) -> [String] {
        items.flatMap { item in
            item.types.compactMap { type -> String? in
                let normalized = type.rawValue.lowercased()
                guard normalized == NSPasteboard.PasteboardType.string.rawValue.lowercased()
                    || normalized.contains("plain-text")
                    || normalized.contains("utf8-plain-text")
                    || normalized == "nsstringpboardtype" else {
                    return nil
                }
                return item.string(forType: type)?.trimmingCharacters(in: .whitespacesAndNewlines)
            }
        }
        .filter { !$0.isEmpty }
    }

    private static func isLikelySecretText(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard (4...256).contains(trimmed.count) else {
            return false
        }
        guard !looksLikeURL(trimmed), !looksLikeEmail(trimmed), !trimmed.hasPrefix("/") else {
            return false
        }

        let hasWhitespace = trimmed.rangeOfCharacter(from: .whitespacesAndNewlines) != nil
        if trimmed.allSatisfy(\.isNumber), (6...8).contains(trimmed.count) {
            return true
        }
        if hasWhitespace {
            return false
        }
        if looksLikePassphrase(trimmed) {
            return true
        }
        return looksHighEntropy(trimmed)
    }

    private static func looksLikeURL(_ text: String) -> Bool {
        guard let url = URL(string: text), url.scheme != nil else {
            return false
        }
        return url.host != nil || url.isFileURL
    }

    private static func looksLikeEmail(_ text: String) -> Bool {
        let parts = text.split(separator: "@")
        guard parts.count == 2 else {
            return false
        }
        return parts[1].contains(".")
    }

    private static func looksLikePassphrase(_ text: String) -> Bool {
        let separators = CharacterSet(charactersIn: "-_.:")
        let segments = text.components(separatedBy: separators).filter { !$0.isEmpty }
        guard segments.count >= 3, text.count >= 16 else {
            return false
        }
        return segments.allSatisfy { segment in
            segment.allSatisfy { $0.isLetter || $0.isNumber }
        }
    }

    private static func looksHighEntropy(_ text: String) -> Bool {
        guard text.count >= 12 else {
            return false
        }

        let classes = [
            text.contains(where: \.isLowercase),
            text.contains(where: \.isUppercase),
            text.contains(where: \.isNumber),
            text.contains { !$0.isLetter && !$0.isNumber }
        ].filter { $0 }.count

        guard classes >= 3 else {
            return false
        }

        let uniqueRatio = Double(Set(text).count) / Double(text.count)
        guard uniqueRatio >= 0.45 else {
            return false
        }

        return shannonEntropy(text) >= 3.0
    }

    private static func shannonEntropy(_ text: String) -> Double {
        let total = Double(text.count)
        let counts = Dictionary(grouping: text, by: { $0 }).mapValues { Double($0.count) }
        return counts.values.reduce(0) { entropy, count in
            let probability = count / total
            return entropy - probability * log2(probability)
        }
    }
}
