import AppKit
import BryanToolsShared
import Carbon
import ClipboardHistoryCore
import SwiftUI

struct ClipboardHistorySettingsView: View {
    @ObservedObject var environment: ClipboardHistoryModule
    @State private var recordingShortcut: ShortcutTarget?

    var body: some View {
        VStack(alignment: .leading, spacing: 18) {
            Text("Clipboard History")
                .font(.system(size: 22, weight: .semibold))

            settingsSection("Shortcuts") {
                settingsRow("Open History") {
                    shortcutControls(
                        hotKey: environment.hotKey,
                        target: .openHistory,
                        reset: environment.resetHotKey
                    )
                }

                settingsRow("Paste Plain Text") {
                    shortcutControls(
                        hotKey: environment.plainTextPasteHotKey,
                        target: .pastePlainText,
                        reset: environment.resetPlainTextPasteHotKey
                    )
                }
            }

            settingsSection("Storage") {
                settingsRow("Location") {
                    VStack(alignment: .trailing, spacing: 8) {
                        Text(environment.storagePath)
                            .font(.system(.caption, design: .monospaced))
                            .lineLimit(2)
                            .multilineTextAlignment(.trailing)
                            .textSelection(.enabled)

                        HStack(spacing: 8) {
                            Button {
                                environment.chooseStorageLocation()
                            } label: {
                                Label("Choose", systemImage: "folder")
                            }

                            Button {
                                environment.resetStorageLocation()
                            } label: {
                                Label("Reset", systemImage: "arrow.counterclockwise")
                            }
                        }
                    }
                }

                settingsRow("Retention") {
                    Stepper(value: retentionBinding, in: ClipboardHistoryPreferences.minimumRetentionDays...ClipboardHistoryPreferences.maximumRetentionDays) {
                        Text("\(environment.retentionDays) days")
                    }
                }

                HStack {
                    Spacer()
                    Button(role: .destructive) {
                        environment.clearHistory()
                    } label: {
                        Label("Clear History", systemImage: "trash")
                    }
                }
            }

            settingsSection("Privacy") {
                Text("Clipboard History skips transient, concealed, autogenerated, 1Password, and likely password-manager clipboard content by default.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }

            if let message = environment.lastErrorMessage {
                settingsSection("Last Error") {
                    Text(message)
                        .font(.caption)
                        .foregroundStyle(.red)
                        .textSelection(.enabled)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }

            Spacer(minLength: 0)
        }
        .padding(22)
        .frame(maxWidth: .infinity, alignment: .topLeading)
        .background(Color(nsColor: .windowBackgroundColor))
        .background(
            Group {
                if recordingShortcut != nil {
                    KeyEventHandlingView { event in
                        handleHotKeyEvent(event)
                    }
                }
            }
        )
    }

    private func settingsSection<Content: View>(_ title: String, @ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 10) {
            Text(title)
                .font(.system(size: 13, weight: .semibold))
                .foregroundStyle(.secondary)

            VStack(spacing: 10) {
                content()
            }
        }
    }

    private func settingsRow<Content: View>(_ title: String, @ViewBuilder content: () -> Content) -> some View {
        HStack(alignment: .firstTextBaseline, spacing: 16) {
            Text(title)
                .frame(width: 140, alignment: .leading)
                .foregroundStyle(.primary)

            Spacer(minLength: 8)

            content()
        }
    }

    private func shortcutControls(hotKey: AppHotKey, target: ShortcutTarget, reset: @escaping () -> Void) -> some View {
        HStack(spacing: 8) {
            Text(hotKey.displayString)
                .font(.system(.body, design: .monospaced))
                .textSelection(.enabled)

            Button {
                recordingShortcut = recordingShortcut == target ? nil : target
            } label: {
                Label(
                    recordingShortcut == target ? "Recording" : "Record",
                    systemImage: recordingShortcut == target ? "record.circle" : "keyboard"
                )
            }

            Button {
                recordingShortcut = nil
                reset()
            } label: {
                Label("Reset", systemImage: "arrow.counterclockwise")
            }
        }
    }

    private var retentionBinding: Binding<Int> {
        Binding(
            get: { environment.retentionDays },
            set: { environment.updateRetentionDays($0) }
        )
    }

    private func handleHotKeyEvent(_ event: NSEvent) -> Bool {
        if event.keyCode == UInt16(kVK_Escape) {
            recordingShortcut = nil
            return true
        }

        guard let hotKey = AppHotKey(event: event),
              let recordingShortcut else {
            return true
        }

        switch recordingShortcut {
        case .openHistory:
            environment.updateHotKey(hotKey)
        case .pastePlainText:
            environment.updatePlainTextPasteHotKey(hotKey)
        }

        if hotKey.hasPrimaryModifier {
            self.recordingShortcut = nil
        }
        return true
    }
}

private enum ShortcutTarget: Equatable {
    case openHistory
    case pastePlainText
}
